<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.Async" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Horizon.Utility.LogAnylyser\Horizon.Utility.LogAnylyser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="csv.test.short.log">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="w3c.test.log">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="w3c.test.short.log">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test.short.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
